name: mmb_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  retrofit: ^4.9.0
  http: ^1.5.0
  retrofit_generator: ^10.1.2
  json_annotation: ^4.9.0
  build_runner: ^2.10.1
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2
  intl: ^0.20.2
  fluttertoast: ^9.0.0
  permission_handler: ^12.0.1
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  url_launcher: ^6.3.2
  flutter_otp_text_field: ^1.5.1+1
  image_picker: ^1.2.1
  extended_image: ^9.0.0
  extended_image_library: ^4.0.0
  path_provider: ^2.1.5
  image_background_remover: ^1.0.0
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  video_player: ^2.9.2
  lottie: ^3.5.1
  pro_image_editor: ^13.2.3
  emoji_picker_flutter: ^3.0.0
  flutter_colorpicker: ^1.1.0
  dotted_border: ^2.1.0
  pinput: ^3.0.0
  image_cropper: ^12.2.1
  gal: ^2.3.2
  device_info_plus: ^12.2.0
  share_plus: ^12.0.2
  archive: ^4.0.9
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/shapes/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/outfit/Outfit-Thin.ttf
          weight: 200
        - asset: assets/fonts/outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/outfit/Outfit-Medium.ttf
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/outfit/Outfit-Bold.ttf
          weight: 500
        - asset: assets/fonts/outfit/Outfit-ExtraBold.ttf
          weight: 600

# 🚀 இது 'flutter:' செக்ஷனுக்கு வெளியே சரியாக அமைக்கப்பட்டுள்ளது
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_logo.png"